/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tp2;


import java.awt.Color;
import javax.swing.JOptionPane;
import tp2.VentanaDeConfiguracion;
/**
 *
 * @author Familia Alpizar R
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        this.getContentPane().setBackground(Color.white);
        initComponents();
        logoBanco.setText(null);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoBanco = new javax.swing.JPanel();
        logoBanco = new javax.swing.JLabel();
        nuevaPersona = new javax.swing.JButton();
        panelCantidadCajas = new javax.swing.JPanel();
        cantidadCajas = new javax.swing.JLabel();
        panelCajasDisp = new javax.swing.JPanel();
        cantidadCajas1 = new javax.swing.JLabel();
        panelCajasOcupadas = new javax.swing.JPanel();
        cajasOcupadas = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        opcionConfiguracion = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        opcioListaClientes = new javax.swing.JMenuItem();
        opcionGTipoCliente = new javax.swing.JMenuItem();
        opcionGClientesAtendidos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de atención al cliente BAC San José");
        setBackground(new java.awt.Color(255, 255, 255));

        infoBanco.setBackground(new java.awt.Color(255, 255, 255));
        infoBanco.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 1, true), "Bienvenido al BAC San Jóse", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        logoBanco.setText("                   Configurar");
        logoBanco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nuevaPersona.setText("Nueva Persona");
        nuevaPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaPersonaActionPerformed(evt);
            }
        });

        panelCantidadCajas.setBackground(new java.awt.Color(255, 255, 255));
        panelCantidadCajas.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Cantidad de cajas "));

        cantidadCajas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cantidadCajas.setText("configurar");

        javax.swing.GroupLayout panelCantidadCajasLayout = new javax.swing.GroupLayout(panelCantidadCajas);
        panelCantidadCajas.setLayout(panelCantidadCajasLayout);
        panelCantidadCajasLayout.setHorizontalGroup(
            panelCantidadCajasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCantidadCajasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cantidadCajas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCantidadCajasLayout.setVerticalGroup(
            panelCantidadCajasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCantidadCajasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cantidadCajas)
                .addContainerGap())
        );

        panelCajasDisp.setBackground(new java.awt.Color(255, 255, 255));
        panelCajasDisp.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Cajas Disponibles"));

        cantidadCajas1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cantidadCajas1.setText("0");

        javax.swing.GroupLayout panelCajasDispLayout = new javax.swing.GroupLayout(panelCajasDisp);
        panelCajasDisp.setLayout(panelCajasDispLayout);
        panelCajasDispLayout.setHorizontalGroup(
            panelCajasDispLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCajasDispLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(cantidadCajas1)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        panelCajasDispLayout.setVerticalGroup(
            panelCajasDispLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCajasDispLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cantidadCajas1)
                .addContainerGap())
        );

        panelCajasOcupadas.setBackground(new java.awt.Color(255, 255, 255));
        panelCajasOcupadas.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Cajas Ocupadas"));

        cajasOcupadas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cajasOcupadas.setText("0");

        jButton1.setText("Liberar una caja");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCajasOcupadasLayout = new javax.swing.GroupLayout(panelCajasOcupadas);
        panelCajasOcupadas.setLayout(panelCajasOcupadasLayout);
        panelCajasOcupadasLayout.setHorizontalGroup(
            panelCajasOcupadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCajasOcupadasLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(panelCajasOcupadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCajasOcupadasLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCajasOcupadasLayout.createSequentialGroup()
                        .addComponent(cajasOcupadas)
                        .addGap(59, 59, 59))))
        );
        panelCajasOcupadasLayout.setVerticalGroup(
            panelCajasOcupadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCajasOcupadasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cajasOcupadas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(12, 12, 12))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/guardia.jpg"))); // NOI18N

        javax.swing.GroupLayout infoBancoLayout = new javax.swing.GroupLayout(infoBanco);
        infoBanco.setLayout(infoBancoLayout);
        infoBancoLayout.setHorizontalGroup(
            infoBancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoBancoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(infoBancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoBancoLayout.createSequentialGroup()
                        .addComponent(logoBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(panelCantidadCajas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelCajasDisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelCajasOcupadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(42, Short.MAX_VALUE))
                    .addGroup(infoBancoLayout.createSequentialGroup()
                        .addComponent(nuevaPersona)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );
        infoBancoLayout.setVerticalGroup(
            infoBancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoBancoLayout.createSequentialGroup()
                .addGroup(infoBancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoBancoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logoBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(infoBancoLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(infoBancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelCajasOcupadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(infoBancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(panelCajasDisp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panelCantidadCajas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(infoBancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nuevaPersona, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jMenu3.setText("Configuración");

        opcionConfiguracion.setText("Configurar datos");
        opcionConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionConfiguracionActionPerformed(evt);
            }
        });
        jMenu3.add(opcionConfiguracion);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Reportes");

        opcioListaClientes.setText("Lista de Clientes");
        opcioListaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcioListaClientesActionPerformed(evt);
            }
        });
        jMenu1.add(opcioListaClientes);

        opcionGTipoCliente.setText("Gráfico según tipo de cliente");
        opcionGTipoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionGTipoClienteActionPerformed(evt);
            }
        });
        jMenu1.add(opcionGTipoCliente);

        opcionGClientesAtendidos.setText("Gráfico de clientes atendidos");
        opcionGClientesAtendidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionGClientesAtendidosActionPerformed(evt);
            }
        });
        jMenu1.add(opcionGClientesAtendidos);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoBanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nuevaPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaPersonaActionPerformed
        InformacionPersona ventana = new InformacionPersona(this,true);
        ventana.setVisible(true);        
    }//GEN-LAST:event_nuevaPersonaActionPerformed

    private void opcionConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionConfiguracionActionPerformed
        VentanaDeConfiguracion config = new VentanaDeConfiguracion(this,true);
        config.setVisible(true);
    }//GEN-LAST:event_opcionConfiguracionActionPerformed

    private void opcioListaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcioListaClientesActionPerformed
        VentanaListaClientes lista = new VentanaListaClientes(this,true);
        lista.setVisible(true);
    }//GEN-LAST:event_opcioListaClientesActionPerformed

    private void opcionGTipoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionGTipoClienteActionPerformed
        VentanaGraficoTipoClientes grafico = new VentanaGraficoTipoClientes(this,true);
        grafico.setVisible(true);
    }//GEN-LAST:event_opcionGTipoClienteActionPerformed

    private void opcionGClientesAtendidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionGClientesAtendidosActionPerformed
        VentanaGrafClientesAtendidos clientes = new VentanaGrafClientesAtendidos(this,true);
        clientes.setVisible(true);
    }//GEN-LAST:event_opcionGClientesAtendidosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Object cjOcupadas = cajasOcupadas.getText();
        if ( cjOcupadas == "0"){
           JOptionPane.showMessageDialog(null, "No hay cajas ocupadas", "Atención", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel cajasOcupadas;
    public javax.swing.JLabel cantidadCajas;
    public javax.swing.JLabel cantidadCajas1;
    private javax.swing.JPanel infoBanco;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JLabel logoBanco;
    private javax.swing.JButton nuevaPersona;
    private javax.swing.JMenuItem opcioListaClientes;
    private javax.swing.JMenuItem opcionConfiguracion;
    private javax.swing.JMenuItem opcionGClientesAtendidos;
    private javax.swing.JMenuItem opcionGTipoCliente;
    private javax.swing.JPanel panelCajasDisp;
    private javax.swing.JPanel panelCajasOcupadas;
    private javax.swing.JPanel panelCantidadCajas;
    // End of variables declaration//GEN-END:variables
}
